  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: nginx-deployment
  spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    replicas: 3
    template:
      spec:
        containers:
        - name: nginx
          image: nginx:1.7.9
          
          
          
          where spec.strategy.rollingUpdate.maxUnavailable is the maximum number of pods that can be unavailable during the update, and spec.strategy.rollingUpdate.maxSurge is the maximum number of pods that can be scheduled above the desired number of pods. 
